language: cpp

cache: apt
cache:
       directories:
         - ThirdLibary/src
         - ThirdLibary

jdk: oraclejdk7

compiler:
  - g++

os:
  - linux

env:
  matrix:
    - BUILD_TARGERT=unix QMAKE=qmake RABBITIM_BUILD_THIRDLIBARY=true RABBITIM_USE_REPOSITORIES="FALSE"
    - BUILD_TARGERT=windows_mingw QMAKE=qmake RABBITIM_BUILD_THIRDLIBARY=true RABBITIM_USE_REPOSITORIES="FALSE"
    #- BUILD_TARGERT=android QMAKE=qmake RABBITIM_BUILD_THIRDLIBARY=true RABBITIM_USE_REPOSITORIES="FALSE" ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a 
    #- BUILD_TARGERT=unix QMAKE=qmake RABBITIM_BUILD_THIRDLIBARY=true
    #- BUILD_TARGERT=windows_mingw QMAKE=qmake RABBITIM_BUILD_THIRDLIBARY=true
    #- BUILD_TARGERT=android QMAKE=qmake RABBITIM_BUILD_THIRDLIBARY=true ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a 
    - BUILD_TARGERT=unix QMAKE=qmake
    - BUILD_TARGERT=windows_mingw QMAKE=qmake
    - BUILD_TARGERT=android QMAKE=qmake ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a 
    - BUILD_TARGERT=unix QMAKE=cmake
    - BUILD_TARGERT=windows_mingw QMAKE=cmake
    - BUILD_TARGERT=android QMAKE=cmake ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

install:
  - source ThirdLibary/build_script/travis/build-depends.sh

before_script:
  - source ThirdLibary/build_script/travis/build-before.sh

script:
  - source ThirdLibary/build_script/travis/build-and-test.sh

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always
