sudo: required
dist: trusty

language: 
    - java
    - android
    - cpp

cache:
       directories:
         - ThirdLibrary/src
         - ThirdLibrary

jdk: oraclejdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- platform-tools
    #- tools
     - build-tools-18.1.1
     - android-18
     - extra

compiler:
  - g++

os:
  - linux

env:
  global:
    - TIMEOUT=120000
  matrix:
    - BUILD_TARGERT=windows_mingw QMAKE=qmake RABBITIM_BUILD_THIRDLIBRARY=true RABBITIM_USE_REPOSITORIES="FALSE"
   # - BUILD_TARGERT=windows_mingw QMAKE=cmake RABBITIM_BUILD_THIRDLIBRARY=true RABBITIM_USE_REPOSITORIES="FALSE"
   # - BUILD_TARGERT=windows_mingw QMAKE=qmake RABBITIM_BUILD_THIRDLIBRARY=true RABBITIM_USE_REPOSITORIES="TRUE"
    
    - BUILD_TARGERT=android QMAKE=qmake RABBITIM_BUILD_THIRDLIBRARY=true RABBITIM_USE_REPOSITORIES="FALSE" ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a 
   # - BUILD_TARGERT=android QMAKE=cmake RABBITIM_BUILD_THIRDLIBRARY=true RABBITIM_USE_REPOSITORIES="FALSE" ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a 
   # - BUILD_TARGERT=android QMAKE=qmake RABBITIM_BUILD_THIRDLIBRARY=true RABBITIM_USE_REPOSITORIES="TRUE" ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a 
    
    - BUILD_TARGERT=unix QMAKE=qmake RABBITIM_BUILD_THIRDLIBRARY=true RABBITIM_USE_REPOSITORIES="FALSE"
   # - BUILD_TARGERT=unix QMAKE=cmake RABBITIM_BUILD_THIRDLIBRARY=true RABBITIM_USE_REPOSITORIES="FALSE"
   # - BUILD_TARGERT=unix QMAKE=qmake RABBITIM_BUILD_THIRDLIBRARY=true RABBITIM_USE_REPOSITORIES="TRUE"

install:
  - ThirdLibrary/build_script/ci/build-before.sh  > /dev/null  #2>&1

before_script: travis_wait 30 ThirdLibrary/build_script/ci/build-depends.sh  #> /dev/null

script: travis_wait 30 ThirdLibrary/build_script/ci/build-and-test.sh #> /dev/null

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always
