language: cpp

cache: apt
cache:
       directories:
         - ThirdLibary/src
         - ThirdLibary

jdk: oraclejdk7

compiler:
  - g++

os:
  - linux

env:
  matrix:
    - BUILD_TARGERT=unix BUILD_THIRDLIBARY=true
    - BUILD_TARGERT=unix_mingw BUILD_THIRDLIBARY=true RABBITIM_USE_REPOSITORIES=true
    - BUILD_TARGERT=android ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a 
    - BUILD_TARGERT=unix QMAKE=qmake BUILD_THIRDLIBARY=true
    - BUILD_TARGERT=unix_mingw QMAKE=qmake BUILD_THIRDLIBARY=true
    - BUILD_TARGERT=android QMAKE=qmake BUILD_THIRDLIBARY=true ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a 

install:
  - source ThirdLibary/build_script/travis/build-depends.sh

before_script:
  - source ThirdLibary/build_script/travis/build-before.sh

script:
  - source ThirdLibary/build_script/travis/build-and-test.sh

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always
