sudo: required
dist: trusty

language: cpp

cache:
  - apt
  - directories:
    - ThirdLibrary/Tools
    - ThirdLibrary/src
    #- ThirdLibrary/unix
    #- ThirdLibrary/windows_mingw

compiler:
  - g++

jdk: oraclejdk7

os:
  - unix

addons:
  ssh_known_hosts:
    - github.com

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake

  matrix:
    - BUILD_TARGERT="unix" QT_VERSION_DIR=5.8 QT_VERSION=5.8.0
    - BUILD_TARGERT="unix" QT_VERSION_DIR=5.7 QT_VERSION=5.7.0

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - export DISPLAY=:99.0         #安装QT时需要
  - sh -e /etc/init.d/xvfb start #安装QT时需要

install:
  - bash ThirdLibrary/build_script/ci/build-install-apt.sh > /dev/null
  - bash ThirdLibrary/build_script/ci/build-install-tools.sh > /dev/null

before_script:
  - source ${SOURCE_DIR}/ThirdLibrary/build_script/ci/build_env.sh
  - cd ${SOURCE_DIR}/ThirdLibrary/build_script

script: 
  - bash ${SOURCE_DIR}/ThirdLibrary/build_script/ci/build.sh ${SOURCE_DIR}

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

deploy:
  provider: releases
  api_key: 177ce637a8ec54e66ea8693092caf35059cf95d7
  file: 
    - ./build_android/android-build/bin/QtApp-debug.apk
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME = android
    repo: KangLin/rabbitim
    tags: true
